fragment PageParts on Page {
  __typename
  blocks {
    __typename
    ... on PageBlocksSection {
      title
      titleFont
      titleFontSize
      titleFontWeight
      subTitle
      subTitleFont
      subTitleFontSize
      subTitleFontWeight
      content
      bodyFont
      fontSize
      fontWeight
      showTitle
      showSubtitle
      showBody
      foldBody
      cueStyle
      cueLabel
      cueLabelOpen
      groups {
        __typename
        label
        intro
        showIntro
        items {
          __typename
          label
          problem
          handled
          showCopy
        }
      }
      showGroupIntros
      showItemCopy
      meta
      email
      phone
      ctaLabel
      ctaUrl
      showArt
      columns
      enabled
    }
    ... on PageBlocksProcessFlow {
      title
      titleFont
      titleFontSize
      titleFontWeight
      subTitle
      subTitleFont
      subTitleFontSize
      subTitleFontWeight
      orientation
      stepFont
      stepFontSize
      stepFontWeight
      steps {
        __typename
        label
        font
        fontSize
        fontWeight
      }
      dotsPerConnector
      dotSize
      dotRestOpacity
      dotPeakOpacity
      flowSpeed
      connectorGap
      stepSpacing
      content
      fontSize
      fontWeight
      ctaLabel
      ctaUrl
      showTitle
      showSubtitle
      showBody
      foldProcess
      foldBody
      cueStyle
      cueLabel
      cueLabelOpen
      enabled
    }
    ... on PageBlocksCaseStudy {
      industry
      client
      location
      package
      timeline
      challenge
      built
      result
      titleFont
      titleFontSize
      titleFontWeight
      bodyFont
      bodyFontSize
      bodyFontWeight
      labelFont
      labelFontSize
      labelFontWeight
      metaFont
      metaFontSize
      enabled
    }
    ... on PageBlocksTestimonial {
      quote
      attributionName
      attributionOrg
      quoteFontSize
      quoteFontWeight
      metaFontSize
      enabled
    }
  }
}

fragment Page_deParts on Page_de {
  __typename
  blocks {
    __typename
    ... on Page_deBlocksSection {
      title
      titleFont
      titleFontSize
      titleFontWeight
      subTitle
      subTitleFont
      subTitleFontSize
      subTitleFontWeight
      content
      bodyFont
      fontSize
      fontWeight
      showTitle
      showSubtitle
      showBody
      foldBody
      cueStyle
      cueLabel
      cueLabelOpen
      groups {
        __typename
        label
        intro
        showIntro
        items {
          __typename
          label
          problem
          handled
          showCopy
        }
      }
      showGroupIntros
      showItemCopy
      meta
      email
      phone
      ctaLabel
      ctaUrl
      showArt
      columns
      enabled
    }
    ... on Page_deBlocksProcessFlow {
      title
      titleFont
      titleFontSize
      titleFontWeight
      subTitle
      subTitleFont
      subTitleFontSize
      subTitleFontWeight
      orientation
      stepFont
      stepFontSize
      stepFontWeight
      steps {
        __typename
        label
        font
        fontSize
        fontWeight
      }
      dotsPerConnector
      dotSize
      dotRestOpacity
      dotPeakOpacity
      flowSpeed
      connectorGap
      stepSpacing
      content
      fontSize
      fontWeight
      ctaLabel
      ctaUrl
      showTitle
      showSubtitle
      showBody
      foldProcess
      foldBody
      cueStyle
      cueLabel
      cueLabelOpen
      enabled
    }
    ... on Page_deBlocksCaseStudy {
      industry
      client
      location
      package
      timeline
      challenge
      built
      result
      titleFont
      titleFontSize
      titleFontWeight
      bodyFont
      bodyFontSize
      bodyFontWeight
      labelFont
      labelFontSize
      labelFontWeight
      metaFont
      metaFontSize
      enabled
    }
    ... on Page_deBlocksTestimonial {
      quote
      attributionName
      attributionOrg
      quoteFontSize
      quoteFontWeight
      metaFontSize
      enabled
    }
  }
}

fragment SettingsParts on Settings {
  __typename
  siteName
  siteNameFont
  siteNameFontSize
  siteNameFontWeight
  subSiteName
  subSiteName_de
  subSiteNameFont
  subSiteNameFontSize
  subSiteNameFontWeight
  subSiteNameTracking
  showSubSiteNameOnly
  headerLayout
  headerLinksFontSize
  navLinks {
    __typename
    label
    label_de
    url
  }
  footerText
  showFooterLine
  footerTextFontSize
  socialLinks {
    __typename
    platform
    url
  }
  fontPreset
  customFontName
  showLogo
  theme
  baseTextColor
  customBackgroundColor
  enableThemeToggle
  enableLogoAnimation
  enableStatusDot
  enableCascadeReveal
  enableTextHover
  enableCheckPageAnimations
  backgroundStyle
  processFlow {
    __typename
    enabled
  }
  depthBackground {
    __typename
    nodeCount
    connectDistance
    lineOpacity
    nodeOpacity
    nodeColor
    fogColor
  }
  planetarySystems {
    __typename
    systemCount
    maxPlanets
    orbitMinRadius
    orbitMaxRadius
    starColor
    pathOpacity
  }
  headerHeight
  footerHeight
  headerInnerWidth
  siteUrl
  metaTitle
  metaTitle_de
  metaDescription
  metaDescription_de
  ogImage
  addressStreet
  addressCity
  addressPostal
  contactEmail
  contactPhone
}

fragment DataPageParts on DataPage {
  __typename
  lang
  enabled
  eyebrow
  heading
  intro
  sections {
    __typename
    heading
    style
    body
  }
  contactEmail
}

fragment FitCheckParts on FitCheck {
  __typename
  roleQuestion {
    __typename
    questionLabel
    questionLabel_de
    businessLabel
    businessLabel_de
    consultantLabel
    consultantLabel_de
    curiousLabel
    curiousLabel_de
  }
  categoryQuestion {
    __typename
    questionLabel
    questionLabel_de
    comms {
      __typename
      buttonLabel
      buttonLabel_de
      followup {
        __typename
        questionLabel
        questionLabel_de
        option1
        option1_de
        option2
        option2_de
        option3
        option3_de
        option4
        option4_de
      }
    }
    sales {
      __typename
      buttonLabel
      buttonLabel_de
      followup {
        __typename
        questionLabel
        questionLabel_de
        option1
        option1_de
        option2
        option2_de
        option3
        option3_de
        option4
        option4_de
      }
    }
    docs {
      __typename
      buttonLabel
      buttonLabel_de
      followup {
        __typename
        questionLabel
        questionLabel_de
        option1
        option1_de
        option2
        option2_de
        option3
        option3_de
        option4
        option4_de
      }
    }
    ops {
      __typename
      buttonLabel
      buttonLabel_de
      followup {
        __typename
        questionLabel
        questionLabel_de
        option1
        option1_de
        option2
        option2_de
        option3
        option3_de
        option4
        option4_de
      }
    }
    reporting {
      __typename
      buttonLabel
      buttonLabel_de
      followup {
        __typename
        questionLabel
        questionLabel_de
        option1
        option1_de
        option2
        option2_de
        option3
        option3_de
        option4
        option4_de
      }
    }
    content {
      __typename
      buttonLabel
      buttonLabel_de
      followup {
        __typename
        questionLabel
        questionLabel_de
        option1
        option1_de
        option2
        option2_de
        option3
        option3_de
        option4
        option4_de
      }
    }
    several {
      __typename
      buttonLabel
      buttonLabel_de
      followup {
        __typename
        questionLabel
        questionLabel_de
      }
    }
  }
  timeQuestion {
    __typename
    questionLabel
    questionLabel_de
    highLabel
    highLabel_de
    midLabel
    midLabel_de
    lowLabel
    lowLabel_de
    unsureLabel
    unsureLabel_de
  }
  processQuestion {
    __typename
    questionLabel
    questionLabel_de
    noneLabel
    noneLabel_de
    partialLabel
    partialLabel_de
    fullLabel
    fullLabel_de
  }
  goalQuestion {
    __typename
    questionLabel
    questionLabel_de
    solveLabel
    solveLabel_de
    clarityLabel
    clarityLabel_de
    exploreLabel
    exploreLabel_de
    compareLabel
    compareLabel_de
  }
  shortClose {
    __typename
    heading
    heading_de
    body
    body_de
    ctaLabel
    ctaLabel_de
  }
  profiles {
    __typename
    fireFight {
      __typename
      name
      name_de
      tagline
      tagline_de
      description
      description_de
    }
    refine {
      __typename
      name
      name_de
      tagline
      tagline_de
      description
      description_de
    }
    build {
      __typename
      name
      name_de
      tagline
      tagline_de
      description
      description_de
    }
    optimize {
      __typename
      name
      name_de
      tagline
      tagline_de
      description
      description_de
    }
  }
  resultShared {
    __typename
    disclaimer
    disclaimer_de
    ctaLabel
    ctaLabel_de
  }
  confirmPage {
    __typename
    emailSubject
    emailSubject_de
    emailBody
    emailBody_de
    confirmHeading
    confirmHeading_de
    confirmBody
    confirmBody_de
    confirmButton
    confirmButton_de
    resultTag
    resultTag_de
    expiredHeading
    expiredHeading_de
    expiredBody
    expiredBody_de
    backLabel
    backLabel_de
  }
}

fragment ArtParts on Art {
  __typename
  title
  year
  price
  image
  enabled
  showTitle
  showPrice
  showLine
}
