fragment PageParts on Page {
  __typename
  blocks {
    __typename
    ... on PageBlocksSection {
      title
      titleFont
      titleFontSize
      titleFontWeight
      subTitle
      subTitleFont
      subTitleFontSize
      subTitleFontWeight
      content
      bodyFont
      fontSize
      fontWeight
      email
      showArt
      columns
      enabled
    }
    ... on PageBlocksProcessFlow {
      title
      titleFont
      titleFontSize
      titleFontWeight
      orientation
      stepFont
      stepFontSize
      stepFontWeight
      steps {
        __typename
        label
        font
        fontSize
        fontWeight
      }
      enabled
    }
    ... on PageBlocksCaseStudy {
      industry
      location
      package
      timeline
      challenge
      built
      result
      titleFont
      titleFontSize
      titleFontWeight
      bodyFont
      bodyFontSize
      bodyFontWeight
      labelFont
      labelFontSize
      labelFontWeight
      metaFont
      metaFontSize
      enabled
    }
  }
}

fragment Page_deParts on Page_de {
  __typename
  blocks {
    __typename
    ... on Page_deBlocksSection {
      title
      titleFont
      titleFontSize
      titleFontWeight
      subTitle
      subTitleFont
      subTitleFontSize
      subTitleFontWeight
      content
      bodyFont
      fontSize
      fontWeight
      email
      showArt
      columns
      enabled
    }
    ... on Page_deBlocksProcessFlow {
      title
      titleFont
      titleFontSize
      titleFontWeight
      orientation
      stepFont
      stepFontSize
      stepFontWeight
      steps {
        __typename
        label
        font
        fontSize
        fontWeight
      }
      enabled
    }
    ... on Page_deBlocksCaseStudy {
      industry
      location
      package
      timeline
      challenge
      built
      result
      titleFont
      titleFontSize
      titleFontWeight
      bodyFont
      bodyFontSize
      bodyFontWeight
      labelFont
      labelFontSize
      labelFontWeight
      metaFont
      metaFontSize
      enabled
    }
  }
}

fragment SettingsParts on Settings {
  __typename
  siteName
  siteNameFont
  siteNameFontSize
  siteNameFontWeight
  subSiteName
  subSiteName_de
  subSiteNameFont
  subSiteNameFontSize
  subSiteNameFontWeight
  subSiteNameTracking
  showSubSiteNameOnly
  headerLayout
  headerLinksFontSize
  navLinks {
    __typename
    label
    label_de
    url
  }
  footerText
  showFooterLine
  footerTextFontSize
  socialLinks {
    __typename
    platform
    url
  }
  fontPreset
  customFontName
  showLogo
  theme
  baseTextColor
  customBackgroundColor
  headerHeight
  footerHeight
  headerInnerWidth
  siteUrl
  metaTitle
  metaTitle_de
  metaDescription
  metaDescription_de
  ogImage
  addressStreet
  addressCity
  addressPostal
  contactEmail
  contactPhone
}

fragment ArtParts on Art {
  __typename
  title
  year
  price
  image
  enabled
  showTitle
  showPrice
  showLine
}
